In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr *2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 73.5 ms
Wall time: 1.04 s


In [4]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.98795567,  1.72986878,  0.16806683],
       [-0.02564029,  2.04011459, -0.26471898]])

In [5]:
data.dtype

dtype('float64')

In [6]:
data * 10

array([[-9.87955672, 17.29868776,  1.68066826],
       [-0.25640288, 20.40114586, -2.64718979]])

In [7]:
data + data

array([[-1.97591134,  3.45973755,  0.33613365],
       [-0.05128058,  4.08022917, -0.52943796]])

In [9]:
data1 = [6, 7.5, 8, 0, 1]
type(data1)

list

In [10]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [1]:
np.arange(15)

NameError: name 'np' is not defined

In [3]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)
arr1.dtype

dtype('float64')

In [5]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [6]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [7]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
empty_unit32 = np.empty(8, dtype = 'u4')
empty_unit32

array([7274610, 7471207, 7143521, 4587552, 7077993, 7536741, 5046364,
       5505089], dtype=uint32)

In [9]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [11]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [13]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [14]:
arr2 = np.arra([0., 4., 1.], [7., 2., 12.1])

AttributeError: module 'numpy' has no attribute 'arra'

In [15]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [16]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5]

5

In [19]:
arr[5:8]

array([5, 6, 7])

In [20]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [21]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [22]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [24]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [26]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[0][2]

3

In [2]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]])

SyntaxError: invalid syntax (<ipython-input-2-df1e5301bf62>, line 1)

In [3]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
arr
arr[1:6]

NameError: name 'arr' is not defined

In [8]:
arr
arr[1:6]

NameError: name 'arr' is not defined

In [9]:
arr2d
arr2d[:2]

NameError: name 'arr2d' is not defined

In [10]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [11]:
data

array([[-0.90385001,  1.70693166,  0.609458  ,  0.36029551],
       [ 0.31338284,  1.05617585, -1.62548339, -0.5826032 ],
       [-1.08022123, -0.07686191, -0.46083056,  1.65793205],
       [-0.44903375,  0.8340855 ,  1.12487511,  0.31367604],
       [-0.66658013,  0.2580199 , -0.89313757, -0.61440516],
       [-0.22941196, -0.30165016, -2.24252597, -0.59298741],
       [ 0.13885186, -1.14028829,  0.09324955, -0.13926535]])

In [12]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [13]:
data[names == 'Bob']

array([[-0.90385001,  1.70693166,  0.609458  ,  0.36029551],
       [-0.44903375,  0.8340855 ,  1.12487511,  0.31367604]])

In [14]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3:]

array([[0.36029551],
       [0.31367604]])

In [15]:
names != 'Bob'
data[~(names == 'Bob')]

array([[ 0.31338284,  1.05617585, -1.62548339, -0.5826032 ],
       [-1.08022123, -0.07686191, -0.46083056,  1.65793205],
       [-0.66658013,  0.2580199 , -0.89313757, -0.61440516],
       [-0.22941196, -0.30165016, -2.24252597, -0.59298741],
       [ 0.13885186, -1.14028829,  0.09324955, -0.13926535]])

In [16]:
cond = names == 'Bob'
data[~cond]

array([[ 0.31338284,  1.05617585, -1.62548339, -0.5826032 ],
       [-1.08022123, -0.07686191, -0.46083056,  1.65793205],
       [-0.66658013,  0.2580199 , -0.89313757, -0.61440516],
       [-0.22941196, -0.30165016, -2.24252597, -0.59298741],
       [ 0.13885186, -1.14028829,  0.09324955, -0.13926535]])

In [17]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[-0.90385001,  1.70693166,  0.609458  ,  0.36029551],
       [-1.08022123, -0.07686191, -0.46083056,  1.65793205],
       [-0.44903375,  0.8340855 ,  1.12487511,  0.31367604],
       [-0.66658013,  0.2580199 , -0.89313757, -0.61440516]])

In [18]:
data[data < 0] = 0
data

array([[0.        , 1.70693166, 0.609458  , 0.36029551],
       [0.31338284, 1.05617585, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.65793205],
       [0.        , 0.8340855 , 1.12487511, 0.31367604],
       [0.        , 0.2580199 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.13885186, 0.        , 0.09324955, 0.        ]])

In [19]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.31338284, 1.05617585, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.13885186, 0.        , 0.09324955, 0.        ]])