In [2]:
a = np.array([1, 2, 3])
print(a)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [14]:
a = np.array([1, 2, 3], dtype = 'int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# Get  Type
a.dtype

dtype('int32')

In [10]:
a.itemsize

4

In [12]:
a.itemsize

2

In [15]:
a.itemsize

4

In [16]:
a.size

3

In [18]:
# Get total size
a.nbytes

12

In [19]:
b.itemsize

8

In [6]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# Get a specific element [r, c]
a[1, 5]

13

In [22]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [7]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [9]:
a[1, 5] = 20

a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [10]:
*3-d example

SyntaxError: invalid syntax (<ipython-input-10-7df3125570df>, line 1)

In [12]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# Get specific element (work outside in)
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [16]:
# Replace
b[:,1,:] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [22]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s matrix
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [24]:
# Any other number
np.full((2, 2),  99)

array([[99, 99],
       [99, 99]])

In [26]:
np.full((2,2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [31]:
# Any ogher number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [33]:
# Random decimal number
np.random.rand(4,2)

array([[0.14012543, 0.01237476],
       [0.46088688, 0.57746556],
       [0.57626848, 0.55358064],
       [0.56035899, 0.2031331 ]])

In [34]:
np.random.random_sample(a.shape)

array([[0.85301428, 0.73233422, 0.51726993, 0.25891193, 0.82245556,
        0.84326986, 0.39975984],
       [0.07033066, 0.00977706, 0.39645209, 0.40978392, 0.67654925,
        0.33644485, 0.25765817]])

In [38]:
# Random Integer value
np.random.randint(-8,8, size = (4,4))

array([[-7, -3,  7,  5],
       [ 3, -8, -6,  3],
       [-2,  5,  4,  0],
       [-2,  7, -2,  6]])

In [39]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

### Be careful when coppying array

In [56]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [57]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [58]:
a + 2

array([3, 4, 5, 6])

In [59]:
 a - 2

array([-1,  0,  1,  2])

In [60]:
a * 2

array([2, 4, 6, 8])

In [61]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [62]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [63]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [65]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [66]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [67]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [68]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
np.min(stats, axis =0)

array([1, 2, 3])

In [82]:
np.max(stats, axis = 1)

array([3, 6])

In [83]:
np.sum(stats)

21

### Reorganizing Arrays

In [89]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
 
np.vstack((v1, v2, v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from file

In [11]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  9,  8,  7,  6],
       [19, 18, 17, 16, 15, 14, 13, 12, 11],
       [21, 28, 27, 26, 25, 24, 23, 22, 21]])

#### Boolean Masking and Advanced indexing

In [15]:
filedata[ filedata<20]

array([ 1,  2,  3,  4,  5,  9,  8,  7,  6, 19, 18, 17, 16, 15, 14, 13, 12,
       11])

In [18]:
# You can index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1,2,8]]

array([2, 3, 9])

In [21]:
np.any(filedata > 20, axis=1)

array([False, False,  True])

In [24]:
(~(filedata < 20) & (filedata > 10))

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])