In [2]:
import numpy as np

In [11]:
P = np.array([2, 4])

In [12]:
Sx, Sy = 3, 0.5

In [13]:
S = np.array([[Sx, 0], [0, Sy]])

In [14]:
S

array([[3. , 0. ],
       [0. , 0.5]])

In [15]:
P_dash = S.dot(P)

In [16]:
P_dash

array([6., 2.])

### Quiz:
Calculate dot product of 3d point using Python.

In [17]:
P = np.array([2, 4, 8])

Sx, Sy, Sz = 3, 0.5, 2

S = np.array([[Sx, 0, 0], [0, Sy, 0], [0, 0, Sz]])

In [18]:
S

array([[3. , 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 2. ]])

In [19]:
P_dash = S.dot(P)
P_dash

array([ 6.,  2., 16.])